In [2]:
import numpy as np 

In [ ]:

def get_data(N, dimensions):
    return np.random.normal(loc=0.0, scale=1.0, size=[N,dimensions])

data = get_data(100000, 2)
data


array([[-1.17357304,  0.48435793],
       [ 0.25066754, -1.28940625],
       [ 0.08585205,  0.13106426],
       ...,
       [ 0.50765279,  0.34136397],
       [-0.36641901,  0.57929461],
       [-0.69482529, -0.69524079]])

In [34]:
estimated_mean = np.mean(data, axis=0)
estimated_mean

array([0.00367012, 0.0095553 ])

In [33]:
estimated_cov = np.cov(m=data, rowvar=False)
estimated_cov

array([[1.03965848, 0.03595862],
       [0.03595862, 1.02131509]])

In [37]:
# So after changing the N values i observed that as many data you have your estimated_mean and 
# estimated_cov is getting more accurate like mean close to 0 and cov is 1. 

# Sigma =  Var(X) & Cov(X, Y) 
#           Cov(Y, X) & Var(Y)
# this is what is we got as output using np.cov