# Unit 1

In [ ]:
# Ex 1.1
import numpy as np

A = np.random.rand(3, 4, 5)
print(f'{A.shape=}')
print(f'{A=}')


A.shape=(3, 4, 5)
A=array([[[0.17646527, 0.82875894, 0.99449141, 0.03442509, 0.96683057],
        [0.8097956 , 0.12254518, 0.53876581, 0.99007193, 0.30640419],
        [0.90997305, 0.40613392, 0.26986868, 0.30815143, 0.40407858],
        [0.15892723, 0.86250279, 0.06812129, 0.12337418, 0.4228651 ]],

       [[0.98672313, 0.21285622, 0.11243265, 0.82232575, 0.99213939],
        [0.27457517, 0.90516231, 0.58863865, 0.89427542, 0.5961831 ],
        [0.05272445, 0.54918695, 0.41930589, 0.10618048, 0.84555995],
        [0.61243845, 0.83740485, 0.59775485, 0.99134556, 0.71644793]],

       [[0.83722382, 0.51784972, 0.97562849, 0.14450958, 0.8824868 ],
        [0.22537196, 0.33655241, 0.725475  , 0.72892842, 0.92235015],
        [0.38543644, 0.59500901, 0.87048874, 0.59232462, 0.47641993],
        [0.4248214 , 0.62611266, 0.64942954, 0.4384949 , 0.26672422]]])


In [8]:
C = np.random.rand(2, 3, 5)
C = C.flatten()
print(f'{C.shape=}')
C = C.reshape(-1, 5)
print(f'{C.shape=}')

C.shape=(30,)
C.shape=(6, 5)


In [9]:
A = np.arange(12).reshape(3, 4)
last_col_1d = A[:, 3]
last_col_2d = A[:, 3:4]
print("A:\n", A)
print("last_col_1d shape:", last_col_1d.shape)
print("last_col_2d shape:", last_col_2d.shape)

B = np.random.randn(2, 3, 4)
page_2 = B[1, :, :]
print("page_2 shape:", page_2.shape)

A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
last_col_1d shape: (3,)
last_col_2d shape: (3, 1)
page_2 shape: (3, 4)


In [15]:
# Ex 1.5
A = np.random.rand(2,4)
v = np.random.rand(4)
B = A + v
print(f'{A.shape=}')
print(f'{v.shape=}')
print(f'{B.shape=}')
v

A.shape=(2, 4)
v.shape=(4,)
B.shape=(2, 4)


array([0.30916113, 0.21690381, 0.92431037, 0.41813089])

# Unit 3 

In [7]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris() 
iris_feat = iris.data
X = np.ones((iris_feat.shape[0], 4))
X[:, 1:4] = iris_feat[:, :3]
y = iris_feat[:,3]
X, y
XTX = X.T @ X
XTy = X.T @ y
beta_hat =  np.linalg.solve(XTX, XTy)
# print(f'{beta_hat=}')
y_hat = X @ beta_hat
# print(f'{y_hat=}') 

y_pred = beta_hat[0] + beta_hat[1] * 5 + beta_hat[2] * 3.5 + beta_hat[3] * 1.5
y_pred

np.float64(0.2893868177815151)

# Unit 4


In [2]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
X = iris.data
X_mean = np.mean(X, axis=0)
X_centered = X - X_mean.reshape(1, -1)
np.mean(X_centered, axis=0)

array([-1.12502600e-15, -7.60872846e-16, -2.55203266e-15, -4.48530102e-16])

In [3]:
X_mean.shape

(4,)